### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by buenjybar** [gruntjs/grunt-contrib-qunit#121]
Hi

would it be possible to update *grunt-lib-phantomjs* dependency to version *1.0.2*
it seems that the phantomjs : 2.1.2 is pretty old compare to phantomjs-prebuilt 2.1.3

having different version of phantomjs in the same project make phantomjs really unstable.

with regards,

**Comment by Arkni** [comment]
No need for that since we use the caret `^`. So, always the latest version of the package will be installed. See:
* https://github.com/gruntjs/grunt-contrib-qunit/blob/master/package.json#L19 `=>` will install `grunt-lib-phantomjs@1.0.2` (`1.x.x`)
* https://github.com/gruntjs/grunt-lib-phantomjs/blob/master/package.json#L19 `=>` will install `phantomjs-prebuilt@2.1.7` (`2.x.x`)

**Comment by buenjybar** [comment]
thank you for the quick reply.
i will try that soon
