### ISSUE TITLE
9.0.0 removed `qunit.log` callback

### ISSUE THREAD

**Issue by vtintillier** [gruntjs/grunt-contrib-qunit#207]
Hello @Krinkle 

With the last release, we have 23c08c972ebab3675860cab5777bb52283eab945 that removes the `qunit.log` event.

We use it to output each assertion, to get a command line output similar to the browser output. It helps us better understanding when a test fails.

Another side effect is that for a long test with lots of assertions, we had frequent messages in the console, and thus the timeout check at https://github.com/gruntjs/grunt-contrib-qunit/blob/a7ff5a38c48f8899476c38c22ea164e8bf8d3fe3/chrome/bridge.js#L34-L43 would have no issue, thanks to the frequent `qunit.log` event messages. But now, we need to set the `timeout` option to a duration bigger than our longest individual test, otherwise we get the timeout error:

```
>> Chrome timed out, possibly due to:
>> - QUnit is not loaded correctly.
>> - A missing QUnit start() call.
>> - Or, a misconfiguration of this task.
>> There was an error with headless chrome
Fatal error: http://localhost:7050/qunit.html
```

Did I miss an event I can use to replace `qunit.log`? If not, can we keep that in the bridge? Or is there another way to fix our issue?

Thanks

**Comment by vtintillier** [comment]
(also https://github.com/gruntjs/grunt-contrib-qunit/blob/a7ff5a38c48f8899476c38c22ea164e8bf8d3fe3/docs/qunit-options.md?plain=1#L46 still references `qunit.log`)

**Comment by vtintillier** [comment]
> The control mechanism for this inside QUnit is [`QUnit.config.testTimeout`](https://qunitjs.com/api/config/testTimeout/) (global) and [`assert.timeout`](https://qunitjs.com/api/assert/timeout/) (per-test). As such, I believe it is preferred and easier to explain/understand that the qunit-contrib-qunit timeout should be set higher than your highest qunit timeout.

Our only timeout for now is only in our `Gruntfile.js`. I will look at adding timeout configuration in QUnit itself too. My understanding is that you will make changes so that with proper timeouts in QUnit, we would not need to increase the grunt-qunit timeout to a very high value.

> With the last release, we have https://github.com/gruntjs/grunt-contrib-qunit/commit/23c08c972ebab3675860cab5777bb52283eab945 that removes the qunit.log event.

>
>We use it to output each assertion, to get a command line output similar to the browser output. It helps us better understanding when a test fails.

So is it possible for us to keep our "one log per assertion" output?

**Comment by Krinkle** [comment]
> So is it possible for us to keep our "one log per assertion" output?
> We use it to output each assertion, to get a command line output similar to the browser output. It helps us better understanding when a test fails.

I have not previously heard of this as a desired outcome. But, I don't mind at all adding it back in a minor release soon. That'd be no problem.

In general, I recommend using the [`testEnd` event](https://qunitjs.com/api/callbacks/QUnit.on/#the-testend-event) when implementing reporters. These are usually frequent enough to get a sense of where the test is. Each test name is expected to be unique and defined in only one place in the suite files. The failing assertion will also have a stack trace with file/line number to find the line directly. Although in the case of a timeout, indeed if you had a single very long test, you would not know which passing assertions had come before unless you opened the HTML interface in a browser.

I do want to mention that QUnit has native support for data providers now. I have often seen that when long tests are written, it is often due to some level of automation or iteration happening inside of that test, which are perhaps arguably separate test cases. If that's the case for you, consider using [QUnit.test.each()](https://qunitjs.com/api/QUnit/test.each/), which might address this problem for you. This also has the benefit of not having to manually compose assertion messages that incorporate each "case", offers per-case timeouts, offers per-case "re-run" in the browser interface, and more.

Having said that, if you like how you have it, I'm happy to add it back. I removed it on the assumption that viable alternatives exist. When that isn't true, I have no reason to keep it removed. Thanks for reporting this!

Can you share how you use this event, so that I can see how it fits in with the other output, and understand how it looks to developers using it?  I might also add a test based on it.

**Comment by vtintillier** [comment]
Thanks a lot for adding it back 👍

**Comment by vtintillier** [comment]
> I do want to mention that QUnit has native support for data providers now. I have often seen that when long tests are written, it is often due to some level of automation or iteration happening inside of that test, which are perhaps arguably separate test cases. If that's the case for you, consider using [QUnit.test.each()](https://qunitjs.com/api/QUnit/test.each/), which might address this problem for you. This also has the benefit of not having to manually compose assertion messages that incorporate each "case", offers per-case timeouts, offers per-case "re-run" in the browser interface, and more.

Thank you for pointing me to this. We were implementing this on our own for some test to look like JUnit parameterized tests, but this look much cleaner 👍 
And maybe the long tests could be using that as well indeed...
