### ISSUE TITLE
Ability to run Qunit tests without PhantomJS in node environment

### ISSUE THREAD

**Issue by bpeacock** [gruntjs/grunt-contrib-qunit#59]
FEATURE
I'm not sure if this is beyond the scope of this project (I haven't yet studied the internals), but it would be wonderful to be able to run Qunit tests in both PhantomJS and a strict node environment using the consistent grunt-contrib-qunit interface.  How difficult would this be to add?  Am I missing a feature in the documentation?

**Comment by dhowe** [comment]
+1

**Comment by jzaefferer** [comment]
This would only make sense for tests that don't need any browser globals (window, DOM methods etc.). Even then its a big task, since the PhantomJS integration is a central part of this module. And since there's no one actively working on it, this needs a committed developer to work on it for days or weeks with little assistance.

**Comment by Arkni** [comment]
As **Jörn** said, this make sense only in case your tests don't need an interaction with browser globals, In this case you might be interested in using https://github.com/kof/node-qunit which runs your qunit test in node.

Closing for now as there is no one actively working on this. Feel free to ask if you have followup question.
