### ISSUE TITLE
httpBase option might be misleading

### ISSUE THREAD

**Issue by juriejan** [gruntjs/grunt-contrib-qunit#82]
I really like the idea of the `httpBase` option, but I believe that it can be quite misleading and cause some confusion.

My initial expectation was that setting the `httpBase` option to `http://localhost:8000` (for example) would result in all the strings (not only found files) in the `src` option to be appended with this string and passed on to the PhantomJS browser.

I thought that the following would provide the `http://localhost:8000/test.html` to the browser if the `test.html` was located in the `www` directory:
```
connect: {
  server: {
    options: {
      base: 'www'
    }
  }
},
qunit: {
  main: {
    options: {
      httpBase: 'http://localhost:8000/'
    },
    src: ['test.html']
  }
}
```

The previous example does not pass on any tests to the browser.

The only way this option can be useful is if the actual test files are being served by the web server from the root of the project, which I believe is not very often the case.

I also tried the following, which to me seems like the only way that the option could have worked without breaking the (what I suspect to be) Grunt.js convention of only listing source files that are found to actually exist:

```
connect: {
  server: {
    options: {
      base: 'www'
    }
  }
},
qunit: {
  main: {
    options: {
      httpBase: 'http://localhost:8000/'
    },
    files: [{
      expand: true,
      cwd: 'www',
      src: ['test.html']
    }]
  }
}
```

The preceding example unfortunately provides the erroneous `http://localhost:8000//www/test.html` to the browser.

Perhaps I'm missing something here, but I believe that if the `httpBase` option is not used with a dynamically built files object that it won't be very useful.

**Comment by Arkni** [comment]
I don't know if you still need a help with this or not. But I'll try to answer some of the question for future ref.

> My initial expectation was that setting the httpBase option to http://localhost:8000 (for example) would result in all the strings (not only found files) in the src option to be appended with this string and passed on to the PhantomJS browser.

That was made clear in `README`:
```md
#### httpBase
Type: `String`
Default: `false`

Create URLs for the `src` files, all `src` files are prefixed with that base.
```

>I thought that the following would provide the http://localhost:8000/test.html to the browser if the test.html was located in the www directory:

`src: ['test.html']` (first example) will be expanded to an empty object. AFAIK `src` should be a valid `glob` pattern, that expand to `path/to/file`. So it will not work.

>I also tried the following, which to me seems like the only way that the option could have worked without breaking the (what I suspect to be) Grunt.js convention of only listing source files that are found to actually exist:

There is an other rule that says `httpBase` should not be terminated with a `/` (see source code).

One thing you should now is, your configuration of your local web server (in your case you're using `grunt-contrib-connect`) doesn't matter to this plugin. So, you have to configure it correctly (adjust the `base` option) in order to work with this plugin.

Closing this for now, feel free to ask if you have followup questions.
